name: Build documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --no-dev --frozen

      - name: Cache data
        id: cache-data
        uses: actions/cache@v4
        with:
          path: docs/data
          key: ${{ runner.os }}-data

      - name: Sphinx build
        run: |
          uv run sphinx-build docs _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
